# Generated by Django 3.2.3 on 2021-05-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210524_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='country',
        ),
    ]
