# Generated by Django 3.2.3 on 2021-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_orders_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
